### ISSUE TITLE
Merging content from *_additional_metadata.json files into the main BOM

### ISSUE THREAD

**Issue by mcutshaw** [LLNL/Surfactant#144]
### Question
Is there currently any way to merge the content generated by plugins in the `*_additional_metadata.json` format into the main BOM? I tried with the `merge_sbom.py` script without success.

**Comment by nightlark** [comment]
The merge_sbom.py script should probably be removed -- its functionality got turned into the `surfactant merge` command; they are intended for merging the contents of multiple complete SBOMs into a single combined SBOM.

There is not a way to merge content generated by plugins in `{sha256filehash}_additional_metadata.json` files into the main BOM; `jq` or writing a small python script might be the quickest way to get those merged into the main BOM.

After plugin config options/settings functionality is added, those plugins will likely get an option that lets a user choose if they want the information output directly into the `metadata` section of the main BOM, or as separate files.

**Comment by mcutshaw** [comment]
Is there any desire for such a script to be made and merged? Or is that something that should be left out until the plugin config is added?

**Comment by nightlark** [comment]
I haven't needed a script yet, but would merge a PR that adds one to https://github.com/LLNL/Surfactant/tree/main/scripts (or a PR that removes the existing files under that folder).

**Comment by mcutshaw** [comment]
Is the following satisfactory before I open a pull request? https://github.com/LLNL/Surfactant/compare/main...mcutshaw:Surfactant:merge_additional_metadata

**Comment by nightlark** [comment]
My take would be that the resulting SBOM should probably still pass validation. So instead of inserting new fields or overwriting existing fields in the software entry itself, the new information should get appended to the list of metadata objects: e.g. `sbom_data["software"][index].metadata.append(additional_data)`

For SBOMs output by Surfactant, I think we can guarantee that the metadata field with be a list, but it wouldn't hurt to add a check for metadata == None, in which case metadata should be set to `[]` before trying to append data.

**Comment by mcutshaw** [comment]
I did adjust the things you mentioned, retested locally, and opened a pull request.
