### ISSUE TITLE
Adding a web interface to interact with SBOM/JSON files

### ISSUE THREAD

**Issue by RazerNinjas** [LLNL/Surfactant#26]
Currently the only way to modify an initial SBOM is mainly by overwriting the associated JSON file manually. It might be a better idea and more user friendly in the long run to create a web interface where users can open SBOM files and modify them more easily without producing errors in the final JSON. The Web interface could also incorporate other features like invoking the command line functionality over a GUI Web interface.

**Comment by nightlark** [comment]
Some CLI functionality has been added for manipulating SBOMs, which will also later be exposed as a TUI for modifying SBOMs.

Mostly going to be moving away from the embedded web interface, due to limitations with file system access in the browser. For modifying an initial SBOM, a discussion has been opened at https://github.com/LLNL/Surfactant/discussions/296 -- this would likely be a hosted web-based service of some form.
