### ISSUE TITLE
Generate "Uses" Relationships without installPrefix

### ISSUE THREAD

**Issue by douglasdennis** [LLNL/Surfactant#32]
Note: I have framed this as a feature request as I'm unsure if the current behavior is a bug or expected.

**Is your feature request related to a problem? Please describe.**
When I run Surfactant using a config file that only contains an `extractPaths` entry then no "Uses" relationships are generated for imports. To get the "Uses" relationships to be generated I must include an `installPrefix`. This requirement is not currently documented, as far as I can see, so I'm not sure if this is expected.

As I initially read the documentation, I expected `installPrefix` to help in two situations. One, be a way of overriding the generated SBOM's `installPath` to better reflect an actual installation of the software. Two, it would also give the user an opportunity to remove any local information that may be revealed in the extract path. I didn't expect that I had to specify `installPrefix` in order to generate relationships.

**Describe the solution you'd like**
My ideal solution is that the `extractPaths` are used as the `installPath` if an `installPrefix` is not explicitely stated. This would ensure that "Uses" relationships are generated by default. I would include the `extractPaths` in the generated `installPath` of the SBOM unless overriden by the `installPrefix`.

This solution would break existing behavior in two ways:
1. Generate relationships when they used to not.
2. Generate an `installPath` when it used to be an empty list.

Change 1 can be addressed by the user using `--skip_relationships`. Change 2 cannot be easily addressed and I believe that is still acceptable. The current implementation generates no `installPath` information if an `installPrefix` is not provided.
That makes it so that file system hierarchical information is not collected (i.e. the generated SBOM appears to exist in a flat file system). I don't believe that this is especially useful by default and users would rather collect that information without additional configuration.

**Describe alternatives you've considered**
One alternative solution would be to use the extract path solely for the sake of calculating relationships but to not save it as the `installPath`. I believe this would be a more complicated solution as current relationship generating methods appear to rely on the `installPath` field in the software object.

Another solution is to simply update the documentation to better reflect that an `installPrefix` must be provided to ensure that "Uses" relationships are captured.

**Additional context**
If you run Surfactant by passing an extract path directly through the CLI (instead of using a config file), then the extract path is automatically used as the `installPrefix` and relationships are generated. This behavior matches my proposed solution.

I have found that my documentation of existing behavior is consistent on Windows and Linux for PE and ELF binaries, respectively.

The existing documentation does seem to imply the existing behavior is expected. Example 1 in the README demonstrates a bare config file with no `installPrefix` and the generated SBOM has no relationships. Example 2 then shows a config file with an `installPrefix` and the relationships are in fact generated. I would suggest that this behavior be more explicitely stated if it is expected though.

**Comment by nightlark** [comment]
The current behavior is expected, though it seems like changing the default to behave similar to passing an extract path directly through the CLI instead of using a config file would make sense. I'd probably also want to add an option to skip collecting install path information in situations where the container extraction tool doesn't preserve accurate file system hierarchy information.

> This solution would break existing behavior in two ways:
> 
> 1. Generate relationships when they used to not.
> 2. Generate an `installPath` when it used to be an empty list.
> 
> Change 1 can be addressed by the user using `--skip_relationships`. Change 2 cannot be easily addressed and I believe that is still acceptable. The current implementation generates no `installPath` information if an `installPrefix` is not provided. That makes it so that file system hierarchical information is not collected (i.e. the generated SBOM appears to exist in a flat file system). I don't believe that this is especially useful by default and users would rather collect that information without additional configuration.

I think the file system hierarchical information was the reason why the current behavior is to not use the `extractPaths` as the `installPrefix` -- what I found is that extraction tools (particularly for exe/msi installers) don't don't a good job of maintaining relative directory structures between where files would be if the installer had actually be run, so the current behavior opted for not collecting file system hierarchy information that could be incorrect (but would otherwise be acceptable in a `containerPath`).

I have also been considering whether `containerPaths` could be used for establishing `Uses` relationships in some cases, when the relative file paths within the container accurately reflect the file system a program would be installed to. One of the issues I have with the SBOM format is that in a situation with multiple workstations/devices, a combined SBOM has install paths that lump install paths from multiple file systems together.

Some ability to map container path UUIDs to directories within a per-device "virtual" file system for establishing relationships could be cleaner than the current approach of keeping individual SBOMs separate (with possible duplicate software entries) for each system that get merged at the last minute.

**Comment by douglasdennis** [comment]
I haven't played much with the extraction tools for installers, but that does seem difficult. I'm going to plan to put a PR up with my proposed changes and see if we can sort out any issues there.

> Some ability to map container path UUIDs to directories within a per-device "virtual" file system for establishing relationships could be cleaner than the current approach of keeping individual SBOMs separate (with possible duplicate software entries) for each system that get merged at the last minute.

Interesting. Assuming the workstation/device is enumerated as well, could there be a way to build a "Contains" relationship between the software and the device? Then when merging the SBOMs you verify the two software objects are "contained" by the same device before attempting to relate them (for whatever reason that might be)?

**Comment by nightlark** [comment]
Basically add a contains relationship to tie several software entries to a "system" that represents a specific device and use that information to establish relationships? That could work, though I feel like it might need some way for a user to opt-in to that behavior -- some caution would need to be taken by whoever is doing enumeration to make sure software running on a workstation (e.g. configuration utilities) is added to the SBOM under a separate system than the software entries that come from the device.
